reverting gradle-templates back to gradle 2.7 due to gradle-tooling incompatibilities  - see https://discuss.gradle.org/t/nosuchmethoderror-in-testkit-after-2-9-2-10-transition/13505